/* Page rendering shares all prices and calculator behavior with /ceny/. */
const priceMoney=value=>value.toLocaleString('ru-RU')+' ₽';
const servicePresets={
 'zamena-unitaza':['Демонтаж унитаза','Установка унитаза'],
 'zamena-smesitelya':['Демонтаж смесителя','Установка смесителя'],
 'nastroika-davleniya-nasosa':['Настройка рабочего давления станции водоснабжения / насоса повышения давления'],
 'prochistka-sifona':['Прочистка сифона'],
 'ustanovka-vodonagrevatelya':['Установка водонагревателя'],
 'ustanovka-nasosa':['Установка насоса']
};
function presetJobs(service){return (servicePresets[service]||[]).map(name=>allPriceJobs.find(j=>j.name===name)).filter(Boolean);}
function renderCalculator(service=''){
 const initial=presetJobs(service);
 return `<section class="estimate" id="calculator" data-default-service="${service}" tabindex="-1" aria-labelledby="estimate-title"><h2 id="estimate-title">Калькулятор работ</h2><p>Цены сантехника Василия Владимировича в Новотитаровской. Выберите работу или опишите её обычными словами.</p><label for="estimate-task">Что нужно сделать?</label><input type="search" id="estimate-task" autocomplete="off" placeholder="Например, смеситель" aria-controls="estimate-options" aria-describedby="estimate-hint"><p id="estimate-hint">Начните писать и отметьте подходящий вариант ниже. «Замена» добавит демонтаж и установку отдельными строками.</p><p id="estimate-match-count" class="estimate-match-count" role="status" aria-live="polite"></p><div id="estimate-options" role="group" aria-label="Подходящие работы"></div><h3>Выбранные работы</h3><p id="estimate-empty" ${initial.length?'hidden':''}>Пока ничего не выбрано. Отметьте работу в подсказках или в прайсе.</p><div id="estimate-selected" role="group" aria-label="Работы в расчёте">${initial.map(job=>`<label class="estimate-selected-row"><input type="checkbox" data-job="${job.id}" checked><span>${job.name}</span><strong>${job.from?'от ':''}${priceMoney(job.amount)}</strong></label>`).join('')}</div><label class="estimate-trip"><input id="estimate-trip" data-job="${allPriceJobs.at(-1).id}" type="checkbox"><span>Поездка в местный магазин и доставка — от ${allPriceJobs.at(-1).amount} ₽<small>На моём транспорте, с вами или без вас. Покупки оплачиваются отдельно.</small></span></label><div id="estimate-result" role="status" aria-live="polite" aria-atomic="true"><p class="estimate-total">${initial.length?'Предварительно: от '+priceMoney(initial.reduce((sum,j)=>sum+j.amount,0)):'Выберите работы для расчёта'}</p></div><div class="estimate-controls"><button type="button" id="estimate-clear" class="button secondary" disabled>Очистить расчёт</button><a class="text-link" href="${path==='ceny'?'#price-list':'/ceny/#price-list'}">Все работы в прайсе ↗</a></div><p class="estimate-disclaimer">Расчёт за одну единицу каждой выбранной работы. Одна и та же работа учитывается один раз. Это ориентир по прайсу. Цена может немного увеличиться из-за сложности или снизиться при простой работе либо большом объёме задач в одном месте. Итоговую сумму согласуем до начала работы. Без скрытых наценок.</p><a class="text-link estimate-full-link" href="/kalkulyator/?service=${service}">Открыть этот расчёт отдельно ↗</a><noscript><p class="note">Исходные цены видны выше. Для изменения расчёта включите JavaScript или свяжитесь с мастером.</p></noscript></section>`;
}
function priceBreadcrumb(label){return `<div class="price-breadcrumb" aria-label="Хлебные крошки"><a href="/">Главная</a><span aria-hidden="true"> / </span><a href="/ceny/">Цены</a><span aria-hidden="true"> / </span><span>${label}</span></div>`;}
function renderCalculatorPage(){return `<div class="inner prices-page dedicated-calculator">${priceBreadcrumb('Калькулятор')}<h1 class="section-title">Калькулятор сантехнических работ</h1><p class="lede">Мой прайс — ваши задачи. Предварительный расчёт работ сантехника Василия Владимировича в Новотитаровской.</p>${renderCalculator()}<section class="story-block"><h2>Частые задачи</h2><div class="price-links">${Object.entries(servicePresets).map(([key,names])=>`<a class="text-link" href="/kalkulyator/?service=${key}">${key==='zamena-unitaza'?'Замена унитаза':key==='zamena-smesitelya'?'Замена смесителя':names[0]} — от ${priceMoney(presetJobs(key).reduce((sum,j)=>sum+j.amount,0))} ↗</a>`).join('')}</div><a class="article-estimate-button" href="/cena-zamena-unitaza/">Что входит в стоимость замены унитаза ↗</a></section>${footer()}</div>`;}
function renderToiletPricePage(){const rows=presetJobs('zamena-unitaza');return `<div class="inner article prices-page toilet-price-page">${priceBreadcrumb('Замена унитаза')}<h1 class="section-title">Сколько стоит замена унитаза в Новотитаровской</h1><p class="lede">Цены на мои работы — сантехника Василия Владимировича. Это мой прайс, а не средние цены по рынку.</p><section class="price-answer" aria-label="Стоимость замены"><p class="price-answer-total">От ${priceMoney(rows.reduce((sum,j)=>sum+j.amount,0))}</p><p>${rows.map(j=>j.name+' — от '+priceMoney(j.amount)).join('<br>')}</p><p>Работа по замене одного напольного унитаза. Новый унитаз и материалы оплачиваются отдельно. Сумму подтверждаю до начала работы.</p><a class="text-link" href="#calculator">Изменить расчёт ниже ↓</a></section>${renderCalculator('zamena-unitaza')}<section class="story-block"><h2>Что входит в работу</h2><p>Демонтаж старого напольного унитаза и установка нового: подготовка места, сборка и крепление прибора, подключение к существующим выводам воды и канализации, проверка наполнения бачка, смыва и герметичности.</p><p>Вывоз старого прибора, переделка труб, ремонт пола и другие дополнительные задачи не подразумеваются автоматически. Если они нужны, обсудим их отдельно до начала работ.</p></section><section class="story-block"><h2>Что может изменить цену</h2><p>Закисший крепёж, неудобный доступ, неровный пол или необходимость переделать подключение могут усложнить работу. Простая установка или несколько работ за один выезд могут снизить общую стоимость. Ориентир — мой прайс, без скрытых наценок.</p><p>Поездка за материалами и доставка — от ${priceMoney(allPriceJobs.at(-1).amount)}, с вами или без вас. Добавляйте её в расчёт только при необходимости. Покупки оплачиваются отдельно.</p></section><section class="story-block"><h2>Как проходит замена</h2><p>Работаю по Новотитаровской. Можно прислать в мессенджер фотографии унитаза, креплений и подключения — так проще заранее понять задачу.</p><a class="article-estimate-button" href="/sovety/zamena-unitaza/">Реальный случай и порядок замены ↗</a></section>${footer()}</div>`;}
